### ISSUE TITLE
ParseAsString shouldn't throw the parsing exception

### ISSUE THREAD

**Issue by hamzashoukat94** [apimatic/core-interfaces-java#21]
DynamicType interface has a method named `parseAsString` which is throwing the `ParseException`. There is no need to throw the parse Exception because its return type is a string so there is no parsing involved.

**Comment by sufyankhanrao** [comment]
Closing this issue as we have to keep going with the `ParseException` because removing it from the method signature will result in a breaking change for the SDK users.
